### PR TITLE
Misc fixes and update to protk 1.4.2

### PR DESCRIPTION
**Pull request by bgruening**
Hi @iracooke,

sorry this branch started as small fixes to make `planemo lint` happy, but it ended up as a branch with miscellaneous fixes:
- lot of `planemo lint` fixes 
- remove `$threads` in favour of GALAXY_SLOTS
- include protk 1.4.2 as dependency (depends on https://github.com/iracooke/protk-galaxytools/pull/3)

ToDo:
- JAVA_VMEM should also be removed and not set by the user, this should be handled by `tool_conf.xml`
- you can get a DOI for your protk repository than we could use this to cite protk in all of these tools
- help needs to be improved

### CODE REVIEW

**Comment by iracooke** [comment]
Thanks for all these cleanups @bgruening 

I'm a still a bit concerned about the package dependency though.  On my test systems there seems to be a problem with the ruby 2.0 package which causes a problem when attempting to install the protk gem. 

Seems that when ruby is compiled it doesn't pick up system libraries correctly.  For example on my test Ubuntu system I have openssl installed .. but I get this in the ruby 2.0 package install log

```
configuring openssl
Failed to configure openssl. It will not be installed.
configuring pathname
configuring psych
configuring pty
configuring racc/cparse
configuring readline
readline nor libedit not found
Failed to configure readline. It will not be installed.
```

This leads to a ruby build that isn't very useful for much at all because it cannot install gems.  When the protk package goes to install it tries to run 

`gem install protk`

And gets

```
ERROR:  Loading command: install (LoadError)
cannot load such file -- openssl
ERROR:  While executing gem ... (NoMethodError)
    undefined method `invoke_with_build_args' for nil:NilClass
```

Anyway ... I'm afraid we are still not there with having the nice toolshed package install dependencies.

**Comment by bgruening** [comment]
@iracooke the `ruby` package does currently have no dependencies. I can add openssl and libreadline etc and I probably should. The corresponding python-2.7 package has all these goodies, including sqlite3 support. Do you have a list with modules you think a standard ruby installation needs to have?

What is strange, and this is not a Galaxy/TS problem, is that your setup does not pick up the openssl standard lib. So you are not able to compile ruby on your system without Galaxy either. Can you please check if you have everything from this page installed: https://wiki.galaxyproject.org/Admin/Config/ToolDependenciesList ... especially this one: pkg-config 

Our Docker image is based on this (https://github.com/galaxyproject/docker-galaxy-requirements/blob/master/Dockerfile) minimal requirement package and I can perfectly install and protk and ruby in it.

Thanks for testing!
Bjoern

**Comment by iracooke** [comment]
OK Bjoern, 

I eventually got it to work by installing a bunch more packages on my system

sudo apt-get install ruby-dev libpq-dev libffi-dev libgdbm-dev libreadline6-dev libncurses5-dev zlib1g-dev libyaml-dev libssl-dev

Of these I believe that libssl-dev and ruby-dev are essential.

**Comment by bgruening** [comment]
@iracooke thanks for helping me to get this done!
I have updated the ruby package to include many more dependencies. It now is maintained under the IUC owner in the TTS: https://testtoolshed.g2.bx.psu.edu/view/iuc/package_ruby_2_0/

#5 will update your protk dependency to get this ruby build in. Hope it's working now for you ubuntu as well.

**Comment by iracooke** [comment]
@bgruening Thanks for your efforts.  

Can you retarget this PR to the tool_dependencies branch.  I've quarantined tool deps there until we get it working nicely.  I think you are almost there. 

My main concern is to make sure that we have clear working instructions for anyone who uses this.  The ruby-dev package dependency still seems to be lacking. 

I'm still confused as to why I needed to install that and why you did not with your docker image.  Once we figure out that we can update the the wiki 

https://wiki.galaxyproject.org/Admin/Config/ToolDependenciesList

To reflect the requirements.

**Comment by bgruening** [comment]
@iracooke do you have any error message for the missing ruby header? Do you need ruby-dev to compile ruby or protk? I would be very confused why we need ruby-dev to install ruby ...

**Comment by iracooke** [comment]
The problem is not installing ruby itself. It is installing a ruby that is capable of installing gems. 
In my testing ruby-dev was required in order to install the protk gem.  I'm really curious why it worked for you. 

I don't have the exact error because I shut down that instance but the error is related to this.  I think the starting point should be to figure out why you don't see it.  Maybe I need to try again from scratch and see if I can replicate your docker build.  Somehow in one of the packages you have installed I think ruby-dev must have been included.

http://stackoverflow.com/questions/7645918/require-no-such-file-to-load-mkmf-loaderror

**Comment by bgruening** [comment]
Ok, thanks for the info. This means that you do not find the ruby headers from your protk instance. I assume you have `pkg-config` installed?

Good luck with your ASMS talk!

**Comment by iracooke** [comment]
Yes I have pkg-config as well as all the other things listed under "Essential" on the wiki page. 

As I say. I am amazed that this works on your instance.  How did you get these headers if you did not install ruby-dev?

**Comment by bgruening** [comment]
They are installed with the ruby package.

**Pull request merged**
