### PR TITLE
Protk goes conda

### PR DESCRIPTION
**Pull request by bgruening**
This will now use by default the protk conda package and TPP5.0. I haven't touched the tests so far and I have seen a few tools missing tests.

### CODE REVIEW

**Comment by bgruening** [comment]
@iracooke do you mind merging thise?

**Comment by iracooke** [comment]
Sorry I sat on it for so long

**Comment by bgruening** [comment]
Thanks Ira! Can you also update the TS?

**Comment by bgruening** [comment]
@iracooke if you give me access to the TS repo I can also update it if you want. Thanks!

**Comment by iracooke** [comment]
@bgruening I gave you write access to the tpp-prophets repository.   

Unfortunately I haven't had time to do any testing.  Have you tested that the tools still work?

**Comment by bgruening** [comment]
No :( a few tests are missing.
I will try to look at this.

**Comment by bgruening** [comment]
So all tests that are included are working. But there are tests missing for the most crucial tools. Not sure if I can come up with nice tests.

**Pull request merged**
